// examples/vue/src/ssr/SsrPage.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { connectVue } from '@stateref/connect-vue';
import type { SsrModel } from 'stateref-example-shared';

/**
 * The server-rendered page (step 5 of docs/server-sync/PHASE8_5.md).
 *
 * Phase 8.4's review found the trap this guards: a Vue server branch that
 * copied the value once showed the pre-prefetch value even after
 * `onServerPrefetch` had moved it. The connector returns a getter on the
 * server for that reason, so what is rendered here is read at render time.
 */
const props = defineProps<{ model: SsrModel }>();

const profile = connectVue(props.model.watch);
const city = profile(store => store.city);
const zip = profile(store => store.zip);
const derived = connectVue(props.model.derived)(store => store);
const combined = connectVue(props.model.combined)(store => store[0].city);
const upper = connectVue(props.model.combined)(store => store[1].upperCase);

/**
 * The row that says the browser has taken over.
 *
 * `false` on the server and `true` once mounted, which is both the signal a
 * reader waits on and a hydration check in itself: a server that rendered
 * `true` here would be reported as a mismatch. The harness reads the DOM,
 * never a `window` global (DC8-8-01).
 */
const hydrated = ref(false);
onMounted(() => {
  hydrated.value = true;
});
</script>

<template>
  <main>
    <h1>state-ref — Vue SSR과 hydration</h1>
    <p class="note">
      onServerPrefetch로 로드한 값이 서버 HTML에 들어가고, 브라우저가 이어받아도
      같아야 한다.
    </p>
    <section class="card">
      <h2>조회한 서버 값</h2>
      <div class="row">
        <span>도시</span><b data-testid="city">{{ city.value }}</b>
      </div>
      <div class="row">
        <span>우편번호</span><b data-testid="zip">{{ zip.value }}</b>
      </div>
      <div class="row">
        <span>hydration</span><b data-testid="hydrated">{{ hydrated }}</b>
      </div>
    </section>
    <section class="card">
      <h2>파생 값</h2>
      <div class="row">
        <span>createComputed</span>
        <b data-testid="derived">{{ derived.value }}</b>
      </div>
      <div class="row">
        <span>combineWatch</span>
        <b data-testid="combined">
          {{ combined.value }} / 대문자 {{ upper.value }}
        </b>
      </div>
    </section>
  </main>
</template>

// examples/react/src/ssr/SsrPage.tsx
import { useEffect, useMemo, useState } from 'react';
import { connectReact } from '@stateref/connect-react';
import type { SsrModel } from 'stateref-example-shared';

/**
 * The server-rendered page (step 5 of docs/server-sync/PHASE8_5.md).
 *
 * The same component renders on the server and hydrates in the browser. It
 * takes its model as a prop rather than reaching for a module-level
 * singleton: a server render has no unmount, so one client per request is the
 * contract Phase 8.4 arrived at.
 *
 * The model is loaded before this renders - `query.watch` throws otherwise.
 */
export default function SsrPage({ model }: { model: SsrModel }) {
  const useProfile = useMemo(() => connectReact(model.watch), [model]);
  const useDerived = useMemo(() => connectReact(model.derived), [model]);
  const useCombined = useMemo(() => connectReact(model.combined), [model]);
  const profile = useProfile();
  const derived = useDerived();
  const combined = useCombined();
  /**
   * The row that says the browser has taken over.
   *
   * `false` on the server and `true` after the first client commit, which is
   * both the signal a reader waits on and a hydration check in itself: a
   * server that rendered `true` here would be reported as a mismatch. The
   * harness reads the DOM, never a `window` global (DC8-8-01).
   */
  const [hydrated, setHydrated] = useState(false);
  useEffect(() => setHydrated(true), []);

  return (
    <main>
      <h1>state-ref — React SSR과 hydration</h1>
      <p className="note">
        서버가 만든 HTML과 브라우저가 이어받은 화면이 같아야 한다.
      </p>
      <section className="card">
        <h2>조회한 서버 값</h2>
        <div className="row">
          <span>도시</span>
          <b data-testid="city">{profile.city.value}</b>
        </div>
        <div className="row">
          <span>우편번호</span>
          <b data-testid="zip">{profile.zip.value}</b>
        </div>
        <div className="row">
          <span>hydration</span>
          <b data-testid="hydrated">{String(hydrated)}</b>
        </div>
      </section>
      <section className="card">
        <h2>파생 값</h2>
        <div className="row">
          <span>createComputed</span>
          <b data-testid="derived">{derived.value}</b>
        </div>
        <div className="row">
          <span>combineWatch</span>
          <b data-testid="combined">
            {combined[0].city.value} / 대문자{' '}
            {String(combined[1].upperCase.value)}
          </b>
        </div>
      </section>
    </main>
  );
}
